### ISSUE TITLE
exe error

### ISSUE THREAD

**Issue by iperov** [hmmlillian/Neural-Color-Transfer#1]
![NVIDIA Share_2019-10-02_22-51-17](https://user-images.githubusercontent.com/8076202/66072982-324fe600-e567-11e9-81b9-9025bd26f767.jpg)

**Comment by hmmlillian** [comment]
@iperov Could you download the dll from the [HDF5](https://www.hdfgroup.org/downloads/hdf5) to have a try?

**Comment by iperov** [comment]
already tried, after that dll it requires more and more dll's

**Comment by hmmlillian** [comment]
@iperov What environment did you use, Windows 10 64bit?

**Comment by iperov** [comment]
7-64

**Comment by iperov** [comment]
and your program will not work on windows 10, because windows 10 also have not such dll's

**Comment by hmmlillian** [comment]
@iperov We compiled on Windows 10 64bit with Visual Studio 2013. Most external dlls should be included. I will double check it later.

**Comment by iperov** [comment]
a lot of laugh. Compiled...

Did you even test your program on clean windows 10 ??

**Comment by iperov** [comment]
windows is not a linux. 
Windows does not have hdf5 and other compiler environment dlls by default.

**Comment by jdumas** [comment]
I also cannot run the provided exe on my windows machine. @hmmlillian have you looked into adding the missing dlls into the provided .zip?

**Comment by hmmlillian** [comment]
> I also cannot run the provided exe on my windows machine. @hmmlillian have you looked into adding the missing dlls into the provided .zip?

@jdumas I tried to find all the possible dlls which might be used and updated the [exe](https://drive.google.com/file/d/1r7zfDIU_S99hmWKpNXLxMDH-3iuCLSoQ/view?usp=sharing). Please try it again. Hope it can help.

**Comment by jdumas** [comment]
Thanks. Looks like I can run it, but it now fails with the following error message (run without arguments):
```
The number of device is: 1, set device 0.
Total Memory = 0, Free Memory = 3541670297.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0219 14:41:36.201583  8780 common.cpp:36] System entropy source not available, using fallback algorithm to generate seed instead.
F0219 14:41:36.202605  8780 io.cpp:41] Check failed: fd != -1 (-1 vs. -1) File not found: \vgg19\VGG_ILSVRC_19_layers_deploy.prototxt
*** Check failure stack trace: ***
```

**Comment by hmmlillian** [comment]
@jdumas Please follow the instructions in README to download the model first.
