### ISSUE TITLE
CUBLAS_STATUS_SUCCESS(0 vs 13)

### ISSUE THREAD

**Issue by carlblocking** [hmmlillian/Neural-Color-Transfer#3]
作者你好
在使用您的程序处理自己图片的时候，出现 CUBLAS_STATUS_SUCCESS(0 vs 13) 问题，请问可能的原因是哪些呢？网上查询了相关资料并尝试后，并没有解决问题。
本人电脑显卡是1080Ti、操作系统是win10, cuda版本是8.0,并且安装了cublas补丁。假如可以的话，我可以发您两张图片跑一下看下结果吗？

**Comment by hmmlillian** [comment]
@carlblocking, I think you can disable TDR to solve this problem. To disable TDR, you may change the TDR-related registry keys like this https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys, or use NVIDIA Nsight Development Platform (https://docs.nvidia.com/gameworks/content/developertools/desktop/timeout_detection_recovery.htm) if you use NVIDIA GPU on Windows.

**Comment by carlblocking** [comment]
It does work, thank you so much！
