### ISSUE TITLE
Exe question during test process.

### ISSUE THREAD

**Issue by Ronales** [hmmlillian/Neural-Color-Transfer#4]
Dear author, When I execute exe file to test IMG, Should I also build caffe2 environment?

this is some error in executing process:

 Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***

I try to fix this problem by add "engine=caffe" and so on.  but finally, I failed.
Can you give me some solve method? Thanks in advance!

**Comment by hmmlillian** [comment]
@Ronales I think you can disable TDR to solve this problem. To disable TDR, you may change the TDR-related registry keys like this https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys, or use NVIDIA Nsight Development Platform (https://docs.nvidia.com/gameworks/content/developertools/desktop/timeout_detection_recovery.htm) if you use NVIDIA GPU on Windows.

**Comment by Ronales** [comment]
Thanks for your reply！

**Comment by dela165** [comment]
> Thanks for your reply！

请问 问题解决了吗？
