### ISSUE TITLE
Compared experiment question about Mechrez et al. [2017] 

### ISSUE THREAD

**Issue by Ronales** [hmmlillian/Neural-Color-Transfer#5]
Dear author,In your paper,I can see the stylized image from your Mechrez et al. [2017]  code implementation  is this:

![NS_seg_50](https://user-images.githubusercontent.com/20239826/82174324-d8880a80-9902-11ea-9e50-6b0ead8ef161.jpg)

But I use official implementation is this:
paper: Roey Mechrez , Eli Shechtman and Lihi Zelnik-Manor. BMVC 2017.
 author:  Mechrez et al. [2017] 

![image](https://user-images.githubusercontent.com/20239826/82174415-34eb2a00-9903-11ea-83a6-5002311b2b33.png)

high solution output is
![image](https://user-images.githubusercontent.com/20239826/82174669-f86bfe00-9903-11ea-965f-b0d980d3062c.png)

I can find some differences in tree colors(your display is white but the official code is green), meanwhile, some other difference can be found in above-compared images

Did you change some weight or reproduced new code of Mechrez et al. [2017]  code?The default weight is :
![image](https://user-images.githubusercontent.com/20239826/82174495-7a0f5c00-9903-11ea-9f7d-624754d1927b.png)

Thanks in advance!

**Comment by hmmlillian** [comment]
@Ronales The results we used to compare with Mechrez et al. [2017] come from the website they provided: https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Software/photorealism/ID679-supp/  (NS+segment+SPE) 
instead of our own implementation.
