### ISSUE TITLE
Multi-reference Neural Color Transfer

### ISSUE THREAD

**Issue by mnbrshd** [hmmlillian/Neural-Color-Transfer#6]
Hello,

I have been trying to implement the multireference neural color transfer portion of your paper but I can't seem to find any clear details anywhere online of the procedure that you followed and I am also not sure how you constructed a single guidance image from all individual guidance images using Markov Random Fields. Can you guide me, please?

Thanks.

**Comment by hmmlillian** [comment]
@mnbrshd The algorithm and energy function is described in Sec 3.4. To find the optimization for minimizing the energy function is a Conditional Random Field problem that can be solved using a multi-label graph cut to decide which reference image each pixel comes from.
